require(snowfall)
getwd()
paths <- readRDS("Data/paths.rds")
initL <- readRDS("Data/inL.rds")
tcounts <- readRDS("Data/tcounts.rds")
lookup <- readRDS("Data/lookup.rds")
sample.run1000 <- readRDS("Data/sample1000.rds")
source("SampleDirichlet.R")
source("alphaInit.R")
source("getTrans.R")
source("getNbGrids.R")
source("getEmit.R")
source("pFFBSIhmm.R")
sfSetMaxCPUs(number=80)
sfInit(socketHosts=rep(c('ukko177', 'ukko170', 'ukko153', 'ukko134', 'ukko065', 'ukko100', 'ukko024', 'ukko175', 'ukko098', 'ukko099'),each=8), cpus=80,type='SOCK',parallel=T)
sfExport("getTrans", "getEmit", "getNbGrids","SampleDirichlet", "alphaInit")
sfExport("paths","tcounts","initL","sample.run1000","lookup")
print("paths exported")
N <- length(paths)
system.time(sfLapply(1:N, pFFBSIhmm, paths, tcounts, initL, sample.run1000, lookup))
sfStop()

